# Generated by Django 6.0.2 on 2026-09-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('city_hub', models.CharField(max_length=100, verbose_name='City / Economic Hub')),
                ('discom_zone', models.CharField(max_length=20, verbose_name='DISCOM Zone')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('baseline_mw', models.FloatField(default=1000.0, verbose_name='Nominal Baseline (MW)')),
                ('dominant_industry', models.CharField(blank=True, max_length=255, verbose_name='Dominant Industry / Character')),
            ],
            options={
                'verbose_name': 'Gujarat District Hub',
                'verbose_name_plural': 'Gujarat District Hubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('OPTIMAL', 'Optimal')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('action', models.TextField(verbose_name='Dispatch Action')),
                ('impact', models.CharField(max_length=255, verbose_name='Expected Grid Impact')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to='grid_intelligence.district')),
            ],
            options={
                'verbose_name': 'SLDC Dispatch Directive',
                'verbose_name_plural': 'SLDC Dispatch Directives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_timestamp', models.DateTimeField()),
                ('hours_ahead', models.CharField(max_length=10)),
                ('predicted_load_mw', models.FloatField()),
                ('gbm_load_mw', models.FloatField(blank=True, null=True)),
                ('threshold_mw', models.FloatField(default=21500.0)),
                ('peak_alert', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='grid_intelligence.district')),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['forecast_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GridAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('WARNING', 'Warning'), ('NORMAL', 'Normal')], default='WARNING', max_length=20)),
                ('root_cause', models.CharField(max_length=255, verbose_name='Root Cause Attribution')),
                ('deviation_pct', models.FloatField(verbose_name='Deviation (%)')),
                ('actual_load_mw', models.FloatField(verbose_name='Actual Load (MW)')),
                ('expected_load_mw', models.FloatField(verbose_name='Expected Load (MW)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='grid_intelligence.district')),
            ],
            options={
                'verbose_name': 'Grid Anomaly',
                'verbose_name_plural': 'Grid Anomalies',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('demand_mw', models.FloatField(verbose_name='Active Demand (MW)')),
                ('renewable_mw', models.FloatField(default=0.0, verbose_name='Renewable Generation (MW)')),
                ('grid_frequency_hz', models.FloatField(default=50.0, verbose_name='Grid Frequency (Hz)')),
                ('power_factor', models.FloatField(default=0.98, verbose_name='Power Factor')),
                ('thd_pct', models.FloatField(default=3.0, verbose_name='Total Harmonic Distortion (THD %)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='grid_intelligence.district')),
            ],
            options={
                'verbose_name': 'SCADA Telemetry Record',
                'verbose_name_plural': 'SCADA Telemetry Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['district', 'timestamp'], name='grid_intell_distric_e415a8_idx')],
            },
        ),
    ]
